export { default as Add } from './Add';
export { default as Arrow } from './Arrow';
export { default as ArrowDown } from './ArrowDown';
export { default as ArrowRight } from './ArrowRight';
export { default as ArrowTail } from './ArrowTail';
export { default as BarGraphIcon } from './BarGraphIcon';
export { CSVIcon } from './CSVIcon';
export { default as Chevron } from './Chevron';
export { default as Cross } from './Cross';
export { default as Dataset } from './Dataset';
export { default as Api } from './Api';
export { default as Vector } from './Vector';

export { default as Delete } from './Delete';
export { default as Download } from './Download';
export { default as Edit } from './Edit';
export { default as ExternalLink } from './ExternalLink';
export { default as Facebook } from './Facebook';
export { default as FileIcon } from './FileIcon';
export { default as FilterIcon } from './FilterIcon';
export { default as Hamburger } from './Hamburger';
export { default as HomeAffairs } from './HomeAffairs';
export { Icon } from './Icon';
export { IconAdd } from './IconAdd';
export { IconAddOutline } from './IconAddOutline';
export { IconAgriculture } from './IconAgriculture';
export { IconAnimal } from './IconAnimal';
export { IconArrow } from './IconArrow';
export { IconBarChart } from './IconBarChart';
export { IconBigArrow } from './IconBigArrow';
export { IconBookmarkOutline } from './IconBookmarkOutline';
export { IconBookmarkSolid } from './IconBookmarkSolid';
export { IconBullet } from './IconBullet';
export { IconCalendar } from './IconCalendar';
export { IconCategory } from './IconCategory';
export { IconCensus } from './IconCensus';
export { IconCheck } from './IconCheck';
export { IconCheckingLine } from './IconCheckingLine';
export { IconCheckingSolid } from './IconCheckingSolid';
export { IconClock } from './IconClock';
export { IconClose } from './IconClose';
export { IconCloseSolid } from './IconCloseSolid';
export { IconCloud } from './IconCloud';
export { IconCode } from './IconCode';
export { IconCommunication } from './IconCommunication';
export { IconContrast } from './IconContrast';
export { IconDownload } from './IconDownload';
export { IconDropdown } from './IconDropdown';
export { IconExplorer } from './IconExplorer';
export { IconEye } from './IconEye';
export { IconFacebook } from './IconFacebook';
export { IconFilter } from './IconFilter';
export { IconFinance } from './IconFinance';
export { IconForest } from './IconForest';
export { IconFullScreen } from './IconFullScreen';
export { IconFullScreenExit } from './IconFullScreenExit';
export { IconGlobe } from './IconGlobe';
export { IconHealth } from './IconHealth';
export { IconHomeAffairs } from './IconHomeAffairs';
export { IconInfo } from './IconInfo';
export { IconInformation } from './IconInformation';
export { IconLineChart } from './IconLineChart';
export { IconLinkedin } from './IconLinkedin';
export { IconLongArrow } from './IconLongArrow';
export { IconMenu } from './IconMenu';
export { IconMinimize } from './IconMinimize';
export { IconPieChart } from './IconPieChart';
export { IconPopOut } from './IconPopOut';
export { IconRadioOff } from './IconRadioOff';
export { IconRadioOn } from './IconRadioOn';
export { IconScreenReader } from './IconScreenReader';
export { IconSearch } from './IconSearch';
export { IconShare } from './IconShare';
export { IconSitemap } from './IconSitemap';
export { IconSnapshotInfo } from './IconSnapshotInfo';
export { IconSort } from './IconSort';
export { IconStarFull } from './IconStarFull';
export { IconStarHalf } from './IconStarHalf';
export { IconStatistics } from './IconStatistics';
export { IconToggleOff } from './IconToggleOff';
export { IconToggleOn } from './IconToggleOn';
export { IconTransport } from './IconTransport';
export { IconTrendingDown } from './IconTrendingDown';
export { IconTrendingUp } from './IconTrendingUp';
export { IconTwitter } from './IconTwitter';
export { IconUncheck } from './IconUncheck';
export { JSONIcon } from './JSONIcon';
export { default as LawJustice } from './LawJustice';
export { default as Licence } from './Licence';
export { default as LineChartIcon } from './LineChartIcon';
export { default as Link } from './Link';
export { default as Linkedin } from './Linkedin';
export { default as Lock } from './Lock';
export { default as Logout } from './Logout';
export { default as LokSabha } from './LokSabha';
export { default as Minus } from './Minus';
export { PdfIcon } from './PdfIcon';
export { External } from './External';

export { XMLIcon } from './XMLIcon';
export { default as Plus } from './Plus';
export { default as Police } from './Police';
export { default as Reddit } from './Reddit';
export { default as Refresh } from './Refresh';
export { default as Remove } from './Remove';
export { default as ShareIcon } from './ShareIcon';
export { default as SortIcon } from './SortIcon';
export { default as TableViewIcon } from './TableViewIcon';
export { default as Twitter } from './Twitter';
export { default as Update } from './Update';
export { default as Upload } from './Upload';
export { default as VidhanSabha } from './VidhanSabha';
export { default as WomenChild } from './WomenChild';
export { XLSIcon } from './XLSIcon';
export { SVGIcon } from './SVGIcon';
export { default as ZIPIcon } from './ZIPIcon';
export { IconLocation } from './IconLocation';
export { default as Rewrite } from './Rewrite';
export { IconCommunity } from './IconCommunity';
export { IconOpen } from './IconOpen';
export { IconRestricted } from './IconRestricted';
export { IconRegistered } from './IconRegistered';
