version: '3'


services:

  web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: opub-dataportal
      env_file: .env       
      command: sh -c "npm run build && npm start"
      ports:
        - 3000:3000
      # stdin_open: true
  
